apiVersion: apps/v1
kind: Deployment
metadata:
  name: agendatec
  namespace: agendatec-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agendatec
  template:
    metadata:
      labels:
        app: agendatec
    spec:
      containers:
      - name: agendatec
        image: paozuriel/cn2-agendatec:latest   # ← AQUÍ VA TU IMAGEN DE DOCKER HUB
        ports:
        - containerPort: 5000
